services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: db_ce
      MYSQL_USER: ce
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: tail -f /dev/null
    stdin_open: true
    tty: true

volumes:
  db_data:

